services:
  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   # depends_on:
  #   #   - mongodb
  #   volumes:
  #     - ./backend:/app
  #   # environment:
  #   #   - MONGO_URI=mongodb://mongodb:27017/your_database_name
  #   networks:
  #     - app-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - app-network

  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./data/db:/data/db
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge